# Generated by Django 2.1.7 on 2019-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krisi_image_problem', '0002_auto_20190327_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
